#!/bin/bash

###########################################################
###########################################################
##                                                       ##
## THIS SCRIPT SHOULD ONLY BE RUN ON A RASPBERRY PI 3 B+ ##
##                                                       ##
###########################################################
###########################################################

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root."
  echo "Please try again after running:"
  echo "  sudo su"
  exit 1
fi

# Change the hostname to hassio
$old_hostname="$(cat /etc/hostname)"
$new_hostname="hassio"

sed -i "s/$old_hostname/$new_hostname/g" /etc/hostname
sed -i "s/$old_hostname/$new_hostname/g" /etc/hosts
/etc/init.d/hostname.sh start

# Install missing requirements
requirements=("socat" "jq" "curl" "avahi-daemon" "dbus-daemon")
missing=

for cmd in ${requirements[@]}; do
  package="$cmd"
  [[ "$cmd" == "dbus-daemon" ]] && package="dbus"
  [[ $(command -v "$cmd") ]] || missing="$missing$package "
done

if [[ -n "$missing" ]]; then
  echo "Attempting install of: $missing"
  apt-get update
  apt-get install -y $missing
fi

if [[ ! $(command -v docker) ]]; then
  curl -sSL https://get.docker.com | sh
fi

# Check again for missing requirements
requirements=("docker" "bash" "socat" "jq" "curl" "avahi-daemon" "dbus-daemon")
missing=

echo "Checking for all requirements..."
for cmd in ${requirements[@]}; do
  package="$cmd"
  [[ "$cmd" == "dbus-daemon" ]] && package="dbus"
  [[ $(command -v "$cmd") ]] || missing="$missing$package "
done

if [[ -n "$missing" ]]; then
  echo "Could not install requirements: $missing"
  echo "Please install manually and run this script again."
  exit 1
else
  echo "All requirements found!"
fi

# Install Hass.io
echo "Installing Hass.io..."
curl -sL https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/hassio_install | bash -s -- -m raspberrypi3

# Hass.io should now be installed!
echo
ip_addr=$(hostname -I | cut -d ' ' -f1)
cat <<EOT
Hass.io is now installing Home Assistant. This process may take up to 20
minutes. Please visit http://hassio.local:8123/ in your browser and wait
for Home Assistant to load. If the previous URL does not work, please try
http://${ip_addr}:8123/
EOT
